-lオプションの実装
konzo-goriki/ruby-practices pull request #9
Opened 2021-11-10 05:46 UTC by konzo-goriki

lsコマンドに-lオプションを実装した。

2021-11-10 11:29 UTC, u1tnk requested changes

2021-11-10 11:29 UTC, u1tnk commented on 05.ls/lib/ls.rb
> +def convert_strmode_user(mode)
rubocopでひっかかってるのはここですか？
僕も業務でこれ以上短くする必要無いと判断することはありますが、プラクティスなので練習と思って警告消しましょう。

メソッドを短くするアイデアとしては

- if/elseのところを三項演算子とする
- 定数でhashを作ってcase/whenの替わりに利用する。以下が例です。変数名は適当

HOGE_HASH = {
  0 => "-",
  S_IXUSR => "x",
...
}
symbol << HOGE_HASH[mode & (S_IXUSR | S_ISUID)]
```

という感じにすると case/whenが不要になります。

2021-11-10 11:29 UTC, u1tnk commented on 05.ls/lib/ls.rb
> +  files.map do |file|
printするだけの処理であれば map では無く eachで良いですね。

2021-11-10 11:29 UTC, u1tnk commented on 05.ls/lib/ls.rb
> +    sliced_files = []
option lのときは show_long_listing_format_filesにまとまっているので、こちらもshow_files(名前も変えた方が良いですね)に表示するための処理をまとめたいですね。

2021-11-11 05:46 UTC, konzo-goriki reviewed
コメントがPending状態だと他人に見えないのを知りませんでした…すいません……。😥

2021-11-11 05:46 UTC, konzo-goriki commented on 05.ls/lib/ls.rb
> +  symbol << if (mode & S_IRUSR).zero?
```
symbol = []
```

の宣言を省き、
```
symbol << if (mode & S_IRUSR).zero?
```
の行を
```
symbol = if (mode & S_IRUSR).zero?
```
とすればrubocopの警告通りメソッドの行数を20行以内に収めることが可能ですが、コードに統一性をもたせたいと考え修正を保留しました。

2021-11-11 05:46 UTC, konzo-goriki commented on 05.ls/lib/ls.rb
> +  symbol << if (mode & S_IRGRP).zero?
同上です。

2021-11-11 05:46 UTC, konzo-goriki commented on 05.ls/lib/ls.rb
> +  symbol << if (mode & S_IROTH).zero?
同上です。

2021-11-11 15:16 UTC, u1tnk requested changes
変数名は大事なので、確認、修正お願いします 🙏

2021-11-11 15:16 UTC, u1tnk commented on 05.ls/lib/ls.rb
> +CONV_MODE_FILE_TYPE_HASH = {
- 型名を変数/定数名にするのは極力避けたい
- hashも悪くは無いのですが、https://www.otsuka-shokai.co.jp/words/hash.html  的な意味もあるので、マッピング的な意味で _MAP、データテーブル的な意味で _TABLE などの方が比較的良いと思います。
    - メンター何人にどうしてるか聞いた結果です。
    - xxx_TYPES と複数形にするパターンも聞きました。私もやりますが、配列かな？と思われる事もあるので参考まで。


また CONV は略さない方が良いですね。 https://blog.jnito.com/entry/2020/10/20/092724 
というか、CONVは無くても意味が通りそうなので無しで大丈夫です。

2021-11-12 04:39 UTC, konzo-goriki commented on 05.ls/lib/ls.rb
> +CONV_MODE_FILE_TYPE_HASH = {
変数名についての指摘確認しました。
xxx_HASHはxxx_TABLEに修正しました。

また、CONVについては省略する方向で修正しました。
今後は省略形については気をつけて使っていきます。

2021-11-13 02:39 UTC, u1tnk approved these changes

2021-11-16 04:52 UTC, closed without merging